import { useState, useRef, useEffect } from "react";
import { Link } from "wouter";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Progress } from "@/components/ui/progress";
import {
  Activity, BarChart2, Bell, Brain, Briefcase, FlaskConical,
  GraduationCap, LineChart, Settings, Shield, ShieldCheck, Signal,
  Target, Terminal, ClipboardList, BookOpen, HelpCircle, Search,
  ChevronDown, ChevronUp, CheckCircle2, ArrowRight, Lightbulb,
  MessageSquare, Send, Zap, Globe, Cpu, AlertTriangle, TrendingUp,
  Star, Info, Layers, SquareStack, Map, Sparkles, Lock, Award,
} from "lucide-react";
import { cn } from "@/lib/utils";

// ─── MODULE CATALOG ────────────────────────────────────────────────────────────
const MODULES = [
  {
    id: "dashboard", label: "Dashboard", path: "/", group: "Core", icon: Activity,
    emoji: "📊", color: "text-blue-400",
    purpose: "Central command center for your entire trading system.",
    description: "Monitor live prices, 7-day P&L, open positions, AI confidence scores, and recent platform activity — all in one view.",
    features: ["Live crypto price heat map", "Portfolio value & P&L chart", "AI market overview panel", "Recent activity feed", "Risk & win-rate metrics"],
    connectedTo: ["Market Data", "AI Center", "Portfolio", "Risk Center", "Analytics"],
    tips: ["Check the AI Market Overview panel every morning for sentiment shifts.", "The heat map colors help you quickly spot movers — red = drop, green = gain.", "Click any metric card to drill into that module."],
  },
  {
    id: "market", label: "Market Data", path: "/market", group: "Core", icon: LineChart,
    emoji: "📈", color: "text-green-400",
    purpose: "Real-time live prices, candles, and technical indicators.",
    description: "Track OHLCV candles for 8 crypto pairs across multiple timeframes, powered by Bybit market data synced every 60 seconds.",
    features: ["Live price grid with 24h stats", "Candlestick chart per symbol", "EMA, RSI, MACD, ADX, ATR indicators", "4 timeframes: 1m, 5m, 1h, 4h", "Volume and trend signals"],
    connectedTo: ["AI Center", "Signals Feed", "Dashboard"],
    tips: ["Use 4h timeframe for swing trade context, 1h for entries.", "Watch ADX > 25 for strong trend confirmation.", "RSI between 45–68 is the healthy bullish zone."],
  },
  {
    id: "ai", label: "AI Center", path: "/ai", group: "Intelligence", icon: Brain,
    emoji: "🤖", color: "text-purple-400",
    purpose: "14-agent AI market analysis and trade decision engine.",
    description: "Run a full multi-agent market analysis on any symbol and timeframe. 14 specialized agents (Market Structure, Price Action, SMC, Volume, Momentum, Trend, Derivatives, Sentiment, Macro, Correlation, Pattern, ML, Risk) vote on a final decision.",
    features: ["14 specialized AI agents", "Consensus scoring engine", "Trade proposal with entry/SL/TP", "3-scenario simulation", "Decision history log", "Explainability breakdown"],
    connectedTo: ["Signals Feed", "Paper Trading", "Learning Center", "Risk Center"],
    tips: ["BUY/SELL signals only fire when ≥60% consensus and risk approved.", "High disagreement = NO TRADE — respect that.", "Use alongside Risk Center to size positions correctly."],
  },
  {
    id: "signals", label: "Signals Feed", path: "/signals", group: "Intelligence", icon: Signal,
    emoji: "📡", color: "text-yellow-400",
    purpose: "Generated trade signals with confidence scores and reasoning.",
    description: "View all BUY/SELL/HOLD signals generated by the AI system, with confidence levels, supporting reasons, and status tracking.",
    features: ["Signal type: BUY / SELL / HOLD", "Confidence score per signal", "Reason chain for each signal", "Status: pending / triggered / expired", "Symbol and strategy tagging"],
    connectedTo: ["AI Center", "Trade Journal", "Paper Trading"],
    tips: ["Filter by confidence > 70% for highest-quality signals.", "Cross-reference signals with Market Data charts before acting.", "Expired signals are still useful for pattern review."],
  },
  {
    id: "learning", label: "Learning Center", path: "/learning", group: "Intelligence", icon: GraduationCap,
    emoji: "🎓", color: "text-cyan-400",
    purpose: "AI feedback loop, decision accuracy tracking, and trading education.",
    description: "Track your AI's learning progress, review feedback on past decisions, study learning paths from Beginner to Expert, earn certificates, and fix recurring trading mistakes.",
    features: ["Skill rating & Trading IQ", "AI mentor messages", "Learning paths with lessons", "Achievement system", "Mistake detector", "Quiz engine"],
    connectedTo: ["AI Center", "Trade Journal", "Paper Trading", "Analytics"],
    tips: ["Complete the Beginner path before going live.", "Review AI mentor messages daily — they're personalized.", "The quiz accuracy tracks how well you understand your own strategies."],
  },
  {
    id: "notifications", label: "Notifications", path: "/notifications", group: "Intelligence", icon: Bell,
    emoji: "🔔", color: "text-orange-400",
    purpose: "Platform alerts, AI decisions, and system event notifications.",
    description: "Stay informed about important platform events, AI decisions, trade updates, and system health alerts in one unified notification center.",
    features: ["AI decision alerts", "Trade open/close notifications", "System health warnings", "Signal generation alerts", "Priority filtering"],
    connectedTo: ["Dashboard", "AI Center", "System Monitor"],
    tips: ["Set critical-only filter during live trading to avoid distraction.", "Review daily summary each morning."],
  },
  {
    id: "trades", label: "Trade Journal", path: "/trades", group: "Trading", icon: BarChart2,
    emoji: "📓", color: "text-emerald-400",
    purpose: "Full trade lifecycle — open, manage, and close real trades.",
    description: "Log and manage your complete trade history. Open trades with entry price, quantity, stop loss, and take profit. Close with exit price and auto-calculated P&L.",
    features: ["Open long/short trades", "Stop loss & take profit fields", "Auto P&L calculation on close", "Trade reason tagging", "Win/loss history", "Strategy attribution"],
    connectedTo: ["Signals Feed", "Portfolio", "Analytics", "Risk Center"],
    tips: ["Always attach a trade reason — it helps AI learn from your decisions.", "Close trades at target, not emotion.", "Review losing trades weekly with Analytics."],
  },
  {
    id: "paper-trading", label: "Paper Trading", path: "/paper-trading", group: "Trading", icon: ClipboardList,
    emoji: "📝", color: "text-teal-400",
    purpose: "Simulated trading with full lifecycle — zero real money risk.",
    description: "Practice your strategies in a risk-free environment. Open paper long/short positions, close them with exit prices, and track simulated P&L across all trades.",
    features: ["Open long/short paper trades", "Entry/exit price tracking", "Auto P&L on close", "Strategy and signal linking", "Paper trade history"],
    connectedTo: ["AI Center", "Signals Feed", "Learning Center"],
    tips: ["Use paper trading to validate AI signals before going live.", "Treat paper trades as seriously as real ones — build the habit.", "Compare paper results with backtests for consistency."],
  },
  {
    id: "portfolio", label: "Portfolio", path: "/portfolio", group: "Trading", icon: Briefcase,
    emoji: "💼", color: "text-indigo-400",
    purpose: "Open positions overview, allocation breakdown, and risk-adjusted P&L.",
    description: "Monitor your current open positions across all symbols. See allocation percentages, unrealized P&L, risk exposure, and portfolio-level performance metrics.",
    features: ["Open positions summary", "Allocation by symbol", "Unrealized P&L tracking", "Risk-adjusted returns", "Portfolio heat map"],
    connectedTo: ["Trade Journal", "Risk Center", "Analytics", "Dashboard"],
    tips: ["Keep no single position > 20% of portfolio — diversify.", "Monitor unrealized drawdown vs your max drawdown limit.", "Re-balance quarterly using Analytics data."],
  },
  {
    id: "risk", label: "Risk Center", path: "/risk", group: "Trading", icon: ShieldCheck,
    emoji: "🛡️", color: "text-red-400",
    purpose: "Position sizing calculator, risk rules, and daily P&L limits.",
    description: "Calculate correct position sizes based on account size, risk %, entry/SL. View active risk rules and daily loss limits to protect your capital.",
    features: ["Position size calculator", "Risk % per trade", "Stop loss distance calculation", "Daily P&L limit display", "Active risk rules", "Max drawdown tracker"],
    connectedTo: ["AI Center", "Trade Journal", "Portfolio"],
    tips: ["Never risk more than 1–2% per trade on any single position.", "Use the calculator BEFORE entering every trade.", "When daily loss limit is hit, stop trading — no exceptions."],
  },
  {
    id: "strategies", label: "Strategies", path: "/strategies", group: "Research", icon: Target,
    emoji: "🎯", color: "text-violet-400",
    purpose: "Strategy library with CRUD, win rate tracking, and active toggling.",
    description: "Create, manage and track all your trading strategies. Each strategy stores entry/exit rules, win rate, profit factor, and total trades. Toggle active strategies for the AI to reference.",
    features: ["Strategy CRUD (create/edit/delete)", "Win rate & profit factor", "Total trade count", "Active/inactive toggle", "Strategy versioning", "Backtest linking"],
    connectedTo: ["Backtesting", "Signals Feed", "Trade Journal", "Research Lab"],
    tips: ["Only activate strategies that have been backtested.", "Profit factor > 1.5 is the target minimum.", "Review and update strategies after 50+ trades."],
  },
  {
    id: "backtests", label: "Backtesting", path: "/backtests", group: "Research", icon: Terminal,
    emoji: "⚙️", color: "text-slate-400",
    purpose: "Run backtests against strategies and view historical results.",
    description: "Test strategies against historical data (simulated walk-forward). View win rate, profit factor, Sharpe ratio, max drawdown, and total return per backtest run.",
    features: ["Backtest against any strategy", "Symbol and timeframe selection", "Win rate, profit factor, drawdown", "Sharpe ratio calculation", "Historical results archive", "Date range selection"],
    connectedTo: ["Strategies", "Analytics", "Research Lab"],
    tips: ["Run at least 3 backtests per strategy across different symbols.", "Sharpe > 1.0 = acceptable risk-adjusted return.", "Compare backtest results to paper trading results for validation."],
  },
  {
    id: "analytics", label: "Analytics", path: "/analytics", group: "Research", icon: BarChart2,
    emoji: "📉", color: "text-pink-400",
    purpose: "Cumulative P&L curves, drawdown, Sharpe, and strategy comparison.",
    description: "Deep-dive performance analytics. View cumulative P&L chart, daily bar chart, max drawdown curve, Sharpe ratio, and compare multiple strategies side by side.",
    features: ["Cumulative P&L curve", "Daily P&L bar chart", "Max drawdown tracker", "Sharpe ratio display", "Strategy comparison chart", "Win/loss breakdown"],
    connectedTo: ["Trade Journal", "Strategies", "Backtesting", "Portfolio"],
    tips: ["Review analytics weekly, not daily — reduce noise.", "Drawdown > 20% = pause trading and review strategy.", "Use strategy comparison to find your best-performing system."],
  },
  {
    id: "research", label: "Research Lab", path: "/research", group: "Research", icon: FlaskConical,
    emoji: "🔬", color: "text-amber-400",
    purpose: "Strategy experiments with hypothesis tracking and verdict workflow.",
    description: "Design and track strategy experiments. Write a hypothesis, define the change, run a backtest, and assign a verdict: Pending → Approved or Rejected.",
    features: ["Experiment CRUD", "Hypothesis writing", "Change tracking", "Backtest linking", "Verdict system (pending/approved/rejected)", "Notes and observations"],
    connectedTo: ["Strategies", "Backtesting", "Analytics"],
    tips: ["Treat every strategy idea as an experiment first — hypothesis before capital.", "Only move Approved experiments to live Strategies.", "Document why experiments were Rejected — future reference."],
  },
  {
    id: "system", label: "System Monitor", path: "/system", group: "System", icon: Settings,
    emoji: "🖥️", color: "text-gray-400",
    purpose: "Service health indicators, uptime, and recent system logs.",
    description: "Monitor the health of all platform services: API Server, Database, Market Data providers, and Realtime connections. View structured system logs with filtering.",
    features: ["Service status grid", "Uptime counter", "Database connectivity", "CoinGecko / Bybit status", "System logs stream", "Log level filtering"],
    connectedTo: ["Dashboard"],
    tips: ["Check System Monitor if market data looks stale.", "Yellow = degraded, red = offline — investigate before trading.", "System logs help debug unexpected behaviors."],
  },
];

const MODULE_GROUPS = ["Core", "Intelligence", "Trading", "Research", "System"];

// ─── KNOWLEDGE BASE ────────────────────────────────────────────────────────────
const ARTICLES = [
  {
    id: "macd", title: "What is MACD?", category: "Technical Analysis", difficulty: "Beginner",
    content: "MACD (Moving Average Convergence Divergence) is a trend-following momentum indicator. It shows the relationship between two EMAs of price. When the MACD line crosses above the signal line, it's a bullish signal. When below, bearish. In this platform, MACD is one of the 14 AI agent inputs — the Momentum agent uses it heavily. A MACD bullish crossover combined with RSI in the 45–68 zone is one of the strongest setups.",
  },
  {
    id: "rsi", title: "How to use RSI", category: "Technical Analysis", difficulty: "Beginner",
    content: "RSI (Relative Strength Index) measures momentum on a 0–100 scale. Above 70 = overbought (potential reversal), below 30 = oversold (potential bounce). In our AI system, RSI between 45–68 is the ideal bullish zone. If RSI > 72, the AI flags overbought risk and may reduce confidence or issue NO TRADE even in a bullish environment.",
  },
  {
    id: "ema", title: "EMA Stacking Explained", category: "Technical Analysis", difficulty: "Intermediate",
    content: "When EMA20 > EMA50 > EMA200, this is called a Bullish EMA Stack — one of the strongest trend confirmation signals. The platform's Trend Agent and Market Structure Agent both look for this alignment. A bullish stack on 4H with ADX > 25 is one of the highest-conviction setups in the system.",
  },
  {
    id: "adx", title: "ADX and Trend Strength", category: "Technical Analysis", difficulty: "Intermediate",
    content: "ADX (Average Directional Index) measures trend strength, not direction. ADX < 20 = weak or ranging market. ADX 20–25 = developing trend. ADX > 25 = strong trend confirmed. In AEGIS QUANT, the AI agents require ADX > 25 for \"strong trend\" classification, which affects how aggressively the system generates BUY/SELL signals.",
  },
  {
    id: "risk-percent", title: "1% Risk Rule", category: "Risk Management", difficulty: "Beginner",
    content: "The 1% rule states: never risk more than 1% of your total account on a single trade. If your account is $10,000, max loss per trade = $100. Use the Risk Center calculator to find the correct position size for any stop loss distance. This rule is what keeps losing streaks from being catastrophic.",
  },
  {
    id: "rr-ratio", title: "Risk-to-Reward Ratio", category: "Risk Management", difficulty: "Beginner",
    content: "R:R ratio compares potential loss to potential gain. A 1:2 R:R means you risk $100 to make $200. Even with a 40% win rate, a 1:2 R:R strategy is profitable. The AI Center's trade proposals always include an expected R:R — filter for R:R > 1.5 for better long-term expectancy.",
  },
  {
    id: "drawdown", title: "Managing Drawdown", category: "Risk Management", difficulty: "Intermediate",
    content: "Drawdown is the peak-to-trough decline in account value. Max drawdown is the largest single drop from a peak. A rule of thumb: if drawdown exceeds 20%, stop trading and review your strategies. In the Analytics module, the drawdown curve shows this visually over time. Set a hard daily loss limit in the Risk Center.",
  },
  {
    id: "ai-pipeline", title: "How the AI Analysis Works", category: "AI & System", difficulty: "Intermediate",
    content: "AEGIS QUANT uses a 14-agent pipeline. Each agent specializes: Market Structure, Price Action, Smart Money Concepts, Volume Intelligence, Momentum, Trend, Derivatives, Sentiment, Macro, Correlation, Pattern Recognition, ML Prediction, Volatility, and Risk Management. Each agent scores the market 0–100. A weighted consensus engine aggregates votes. If consensus > 60% with low disagreement and risk approved, a BUY or SELL is issued. Otherwise: HOLD or NO TRADE.",
  },
  {
    id: "smc", title: "Smart Money Concepts (SMC)", category: "AI & System", difficulty: "Advanced",
    content: "SMC focuses on institutional order flow. Key concepts: Order Blocks (supply/demand zones where institutions placed orders), Fair Value Gaps (price imbalances that often get filled), Liquidity Sweeps (stop hunts above highs or below lows before reversals), and Break of Structure (BoS). The platform's SMC Agent maps these zones automatically and feeds them into the consensus engine.",
  },
  {
    id: "backtesting", title: "Why Backtesting Matters", category: "Platform Features", difficulty: "Beginner",
    content: "Backtesting simulates how a strategy would have performed on historical data. Key metrics: Win Rate (% of profitable trades), Profit Factor (gross profit ÷ gross loss — target > 1.5), Sharpe Ratio (risk-adjusted return — target > 1.0), and Max Drawdown. In AEGIS QUANT, backtests are run per strategy with selectable symbol and timeframe. Always backtest before live trading.",
  },
  {
    id: "paper-trading-guide", title: "Paper Trading Best Practices", category: "Platform Features", difficulty: "Beginner",
    content: "Paper trading lets you test strategies with zero real risk. Best practices: (1) Treat paper trades as seriously as real trades. (2) Use realistic position sizes. (3) Don't skip stop losses just because it's paper. (4) Run at least 50 paper trades before going live on any strategy. (5) Compare your paper results to your backtest results — they should be similar.",
  },
  {
    id: "sharpe", title: "Sharpe Ratio Explained", category: "Technical Analysis", difficulty: "Intermediate",
    content: "The Sharpe ratio measures return per unit of risk. Formula: (Return − Risk-Free Rate) ÷ Standard Deviation. Sharpe < 1 = poor risk-adjusted return. Sharpe 1–2 = acceptable. Sharpe > 2 = excellent. In AEGIS QUANT, the Analytics and Backtesting modules both display Sharpe ratio. Use it to compare strategies — higher is always better.",
  },
  {
    id: "wyckoff", title: "Wyckoff Market Phases", category: "AI & System", difficulty: "Advanced",
    content: "Wyckoff theory describes four market phases: Accumulation (institutions quietly buying), Markup (uptrend), Distribution (institutions selling), and Markdown (downtrend). Within these are sub-phases like Re-accumulation and Re-distribution. The Market Structure Agent in AEGIS QUANT identifies these phases and uses them to contextualize trend direction and expected next move.",
  },
];

const ARTICLE_CATEGORIES = ["All", "Technical Analysis", "Risk Management", "AI & System", "Platform Features"];

// ─── FAQ ───────────────────────────────────────────────────────────────────────
const FAQ_ITEMS = [
  {
    q: "Why does the AI say NO TRADE even when the market looks bullish?",
    a: "NO TRADE fires when there is high agent disagreement (< 55% consensus majority), when RSI is overbought (> 72), or when the Risk Management agent rejects the position based on your risk profile. This is a safety mechanism — forcing you to only trade high-conviction setups.",
  },
  {
    q: "What does 'offline mode' mean for the database?",
    a: "Offline mode means Supabase credentials (SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY) are not set. In offline mode, strategies, trades, signals, and backtests will show empty tables. The Bybit market data worker still runs and live prices still display. To enable full storage, connect a Supabase project.",
  },
  {
    q: "How do I deploy the backend to Render?",
    a: "The backend (api-server) is a Node.js Express app. In Render: create a new Web Service, connect your GitHub repo, set Build Command to 'pnpm --filter @workspace/api-server run build', Start Command to 'pnpm --filter @workspace/api-server run start', and add your SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, BYBIT_API_KEY, BYBIT_API_SECRET as environment variables.",
  },
  {
    q: "How do I connect Vercel (frontend) to my Render backend?",
    a: "In Vercel, add the environment variable VITE_API_BASE_URL and set it to your Render backend URL (e.g. https://your-app.onrender.com/api). The frontend will automatically use this URL for all API calls instead of the local /api proxy.",
  },
  {
    q: "Why do I see sourcemap warnings in the Vercel build log?",
    a: "These are non-fatal warnings about source map resolution in some UI component files. They do not affect the build output or runtime behavior. The build succeeds regardless ('✓ 2521 modules transformed'). You can safely ignore them.",
  },
  {
    q: "How often does market data sync?",
    a: "The Bybit market data worker syncs OHLCV candles for 8 symbols × 4 timeframes = 32 pairs every 60 seconds. Indicators (EMA, RSI, MACD, ADX, ATR) are recalculated after each sync. If Supabase is not connected, market data is fetched live from Bybit but not stored — it works per-request in offline mode.",
  },
  {
    q: "What is the difference between Trade Journal and Paper Trading?",
    a: "Trade Journal is for your real trades — actual capital at risk. Paper Trading is a simulated sandbox with zero real money. Paper trades have the same structure (entry, exit, P&L) but are tracked separately. Use Paper Trading to validate strategies, then graduate winning strategies to the Trade Journal.",
  },
  {
    q: "How do I interpret the AI confidence score?",
    a: "Confidence is the weighted average score from all agent votes, scaled 0–100. < 55 = weak signal, high uncertainty. 55–70 = moderate conviction. 70–85 = strong conviction. > 85 = very high conviction. The platform only fires BUY/SELL when confidence ≥ 60 with strong consensus. Below that threshold, it outputs HOLD.",
  },
  {
    q: "Can I add custom strategies?",
    a: "Yes. In the Strategies module, click 'New Strategy', fill in the name, description, and rules. You can then run backtests against it, activate it for AI signal generation, and track its performance in the Trade Journal and Analytics modules.",
  },
  {
    q: "How does the position size calculator work?",
    a: "In Risk Center, enter: Account Size, Risk % per trade (recommended 1–2%), Entry Price, and Stop Loss Price. The calculator computes: Position Size = (Account × Risk%) ÷ (Entry − Stop Loss). This ensures you never lose more than your defined risk % on any single trade.",
  },
];

// ─── AI ASSISTANT ──────────────────────────────────────────────────────────────
type ChatMessage = { role: "user" | "assistant"; text: string };

const SUGGESTED_QUESTIONS = [
  "How does AI analysis work?",
  "What is the Risk Center?",
  "How do I use Paper Trading?",
  "Explain the EMA stack",
  "What is a good Sharpe ratio?",
  "How do I connect Vercel to Render?",
];

function getAIResponse(question: string): string {
  const q = question.toLowerCase();

  if (q.includes("ai") && (q.includes("work") || q.includes("how") || q.includes("analy"))) {
    return "The AI Center uses a 14-agent pipeline. Each agent specializes in a different analysis domain: Market Structure, Price Action, Smart Money Concepts, Volume, Momentum, Trend, Derivatives, Sentiment, Macro, Correlation, Pattern Recognition, ML Prediction, Volatility, and Risk Management.\n\nEach agent scores the market 0–100 with a direction (bullish/bearish/neutral). A weighted consensus engine aggregates all votes. If the majority confidence ≥ 60% with low disagreement and the Risk agent approves, it outputs BUY or SELL — otherwise HOLD or NO TRADE.";
  }
  if (q.includes("risk center") || (q.includes("risk") && q.includes("calculator"))) {
    return "The Risk Center has two main functions:\n\n1. Position Size Calculator — Enter your account size, risk % per trade, entry price, and stop loss price. It calculates the exact position size to never exceed your risk limit.\n\n2. Risk Rules Display — Shows your active daily P&L limits and max drawdown thresholds.\n\nRule of thumb: risk 1–2% per trade maximum. If the daily loss limit is hit, stop trading for the day — no exceptions.";
  }
  if (q.includes("paper trading") || q.includes("paper trade")) {
    return "Paper Trading is a risk-free simulation environment. You open positions just like real trades (entry price, quantity, stop loss) but no real money moves.\n\nBest practice: run at least 50 paper trades on a strategy before using real capital. Compare your paper results with backtest results — they should be similar. Use the Learning Center to track your paper trading accuracy over time.";
  }
  if (q.includes("ema") && (q.includes("stack") || q.includes("align"))) {
    return "A Bullish EMA Stack means EMA20 > EMA50 > EMA200. This is one of the strongest trend confirmation signals.\n\nWhen all three EMAs are aligned in this order, it indicates multi-timeframe trend agreement. The Trend Agent and Market Structure Agent both look for this alignment. Combined with ADX > 25 on the 4H chart, it's one of the highest-conviction setups in the system.";
  }
  if (q.includes("sharpe")) {
    return "Sharpe Ratio measures return per unit of risk: (Return − Risk-Free Rate) ÷ Standard Deviation.\n\n• Sharpe < 1.0 — poor risk-adjusted return\n• Sharpe 1.0–2.0 — acceptable\n• Sharpe > 2.0 — excellent\n\nIn AEGIS QUANT, both the Analytics and Backtesting modules display Sharpe ratio. Use it to compare strategies objectively — a higher Sharpe always means better risk-adjusted performance.";
  }
  if (q.includes("vercel") || q.includes("render") || q.includes("deploy")) {
    return "To connect Vercel (frontend) to Render (backend):\n\n1. Deploy the backend to Render — set Build Command: pnpm --filter @workspace/api-server run build, Start Command: node artifacts/api-server/dist/index.mjs\n\n2. Add these env vars to Render: SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, BYBIT_API_KEY, BYBIT_API_SECRET\n\n3. In Vercel, add environment variable: VITE_API_BASE_URL = https://your-render-app.onrender.com/api\n\nThe frontend will automatically route all API calls to your Render backend.";
  }
  if (q.includes("supabase") || q.includes("database") || q.includes("offline")) {
    return "Supabase is used as the database for strategies, trades, signals, backtests, AI decisions, and all other persistent data.\n\nIf SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are not set, the system runs in 'offline mode' — live market data still works via Bybit, but all database tables will return empty. To enable full persistence, create a Supabase project and add the credentials as environment variables.";
  }
  if (q.includes("macd")) {
    return "MACD (Moving Average Convergence Divergence) tracks the relationship between two EMAs.\n\n• MACD above signal line → bullish momentum\n• MACD below signal line → bearish momentum\n\nIn AEGIS QUANT, the Momentum Agent uses MACD as one of its core inputs. A bullish MACD crossover combined with RSI in the 45–68 zone and EMA bullish stack is one of the strongest combined signals in the system.";
  }
  if (q.includes("rsi")) {
    return "RSI (Relative Strength Index) measures momentum 0–100.\n\n• RSI > 70 — overbought (caution/reversal risk)\n• RSI 45–68 — ideal bullish zone\n• RSI < 30 — oversold (potential bounce)\n\nIf RSI > 72, the AI Risk agent may reject the trade even in a bullish environment — it's protecting you from chasing overextended moves.";
  }
  if (q.includes("no trade") || q.includes("notrade")) {
    return "NO TRADE fires in three situations:\n\n1. High agent disagreement — consensus < 55% majority, meaning agents are split on direction\n2. RSI overbought — RSI > 72 on the selected timeframe\n3. Conservative risk profile + weak trend — risk agent rejects the position\n\nNO TRADE is not a failure — it's the AI protecting you from low-quality setups. Only trade high-conviction signals.";
  }
  if (q.includes("backtest")) {
    return "Backtesting simulates how a strategy would have performed historically.\n\nKey metrics to review:\n• Win Rate — target > 50% for trend strategies\n• Profit Factor — gross profit ÷ gross loss, target > 1.5\n• Sharpe Ratio — risk-adjusted return, target > 1.0\n• Max Drawdown — largest peak-to-trough drop, keep below 20%\n\nAlways run at least 3 backtests across different symbols before going live with any strategy.";
  }
  if (q.includes("strategy") || q.includes("strategies")) {
    return "The Strategies module is your strategy library.\n\nYou can:\n• Create strategies with entry/exit rules\n• Track win rate, profit factor, total trades\n• Toggle strategies active/inactive for AI signal generation\n• Version strategies as they evolve\n• Link strategies to backtests and trade journal entries\n\nBest practice: only activate strategies with a backtest Profit Factor > 1.5 and Sharpe > 1.0.";
  }
  if (q.includes("signal")) {
    return "Signals are generated by the AI Center analysis. Each signal has:\n\n• Signal Type — BUY, SELL, or HOLD\n• Confidence Score — 0–100% (above 60% fires a signal)\n• Reason — key factors that generated the signal\n• Status — pending (awaiting trigger), triggered (price hit level), or expired\n\nFilter signals by confidence > 70% for the highest-quality entries. Always cross-reference with the Market Data chart before acting.";
  }
  if (q.includes("adx")) {
    return "ADX (Average Directional Index) measures trend strength, not direction.\n\n• ADX < 20 — weak or ranging market (avoid trend strategies)\n• ADX 20–25 — developing trend\n• ADX > 25 — strong trend confirmed\n\nAEGIS QUANT AI agents require ADX > 25 for 'strong trend' classification. This filters out noisy, choppy markets where most strategies fail.";
  }
  if (q.includes("hello") || q.includes("hi ") || q === "hi" || q.includes("hey")) {
    return "Hello! I'm your AEGIS QUANT AI platform guide. I can explain any feature, module, or concept on the platform.\n\nTry asking me things like:\n• 'How does AI analysis work?'\n• 'What is a good risk-reward ratio?'\n• 'How do I connect Vercel to Render?'\n• 'Explain MACD'\n• 'What is paper trading?'";
  }
  if (q.includes("portfolio")) {
    return "The Portfolio module shows all your open positions in one view.\n\nYou'll see:\n• Each open position with entry price, current unrealized P&L\n• Allocation breakdown (% of portfolio per symbol)\n• Risk exposure metrics\n• Portfolio-level performance summary\n\nKeep no single position above 20% of total portfolio — diversification reduces risk.";
  }
  if (q.includes("wyckoff") || q.includes("smc") || q.includes("smart money")) {
    return "Smart Money Concepts (SMC) focuses on institutional order flow:\n\n• Order Blocks — zones where institutions placed large orders, acting as support/resistance\n• Fair Value Gaps (FVG) — price imbalances that often get filled\n• Liquidity Sweeps — stop hunts above highs or below lows before reversals\n• Break of Structure (BoS) — market structure shift signaling trend change\n\nThe SMC Agent in AEGIS QUANT maps these zones automatically and contributes 10% weight to the consensus decision.";
  }

  return "I can help explain any feature or concept on the AEGIS QUANT platform. Try asking about:\n\n• A specific module (e.g. 'What is the Risk Center?')\n• A technical indicator (e.g. 'Explain MACD', 'How to use RSI')\n• The AI system (e.g. 'How does AI analysis work?')\n• Deployment (e.g. 'How do I connect Vercel to Render?')\n• Risk management (e.g. 'Explain the 1% rule')\n\nType your question below.";
}

// ─── COMPONENTS ───────────────────────────────────────────────────────────────
function StatBadge({ icon: Icon, label, value }: { icon: React.ElementType; label: string; value: string | number }) {
  return (
    <div className="flex flex-col items-center justify-center rounded-xl border border-border bg-muted/10 p-4 text-center gap-1.5">
      <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center">
        <Icon className="w-4 h-4 text-primary" />
      </div>
      <div className="text-xl font-black tabular-nums">{value}</div>
      <div className="text-[11px] text-muted-foreground">{label}</div>
    </div>
  );
}

// ─── OVERVIEW TAB ──────────────────────────────────────────────────────────────
const GETTING_STARTED = [
  { step: 1, title: "Explore the Dashboard", desc: "Get familiar with your command center — prices, P&L, and AI overview.", path: "/" },
  { step: 2, title: "Check Market Data", desc: "Review live prices and candles for your target symbols.", path: "/market" },
  { step: 3, title: "Run an AI Analysis", desc: "Go to AI Center, select a symbol and timeframe, and run your first analysis.", path: "/ai" },
  { step: 4, title: "Create a Strategy", desc: "Define your entry/exit rules in the Strategies module.", path: "/strategies" },
  { step: 5, title: "Backtest & Paper Trade", desc: "Validate the strategy via Backtesting, then practice in Paper Trading.", path: "/paper-trading" },
  { step: 6, title: "Analyze Performance", desc: "Review your results in Analytics and track growth in Learning Center.", path: "/analytics" },
];

function OverviewTab() {
  return (
    <div className="space-y-6">
      {/* Welcome */}
      <div className="rounded-xl border border-primary/20 bg-primary/5 p-6">
        <div className="flex items-start gap-4">
          <div className="w-12 h-12 rounded-xl bg-primary/20 flex items-center justify-center shrink-0">
            <Map className="w-6 h-6 text-primary" />
          </div>
          <div>
            <h2 className="text-lg font-bold">Welcome to the Guidance Center</h2>
            <p className="text-sm text-muted-foreground mt-1 max-w-2xl">
              Everything you need to master AEGIS QUANT AI — module documentation, interactive AI assistant,
              trading knowledge base, and a step-by-step getting started guide.
            </p>
          </div>
        </div>
      </div>

      {/* Platform stats */}
      <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-6 gap-3">
        <StatBadge icon={Layers} label="Modules" value={15} />
        <StatBadge icon={Brain} label="AI Agents" value={14} />
        <StatBadge icon={Globe} label="Crypto Pairs" value={8} />
        <StatBadge icon={SquareStack} label="Timeframes" value={4} />
        <StatBadge icon={BookOpen} label="KB Articles" value={ARTICLES.length} />
        <StatBadge icon={HelpCircle} label="FAQ Items" value={FAQ_ITEMS.length} />
      </div>

      {/* Getting started */}
      <div>
        <h3 className="text-sm font-semibold mb-3 flex items-center gap-2">
          <Zap className="w-4 h-4 text-primary" /> Getting Started — 6 Steps
        </h3>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">
          {GETTING_STARTED.map((s) => (
            <Link key={s.step} href={s.path}>
              <div className="group rounded-xl border border-border bg-muted/10 p-4 hover:border-primary/30 hover:bg-primary/5 transition-all cursor-pointer h-full">
                <div className="flex items-start gap-3">
                  <div className="w-7 h-7 rounded-full bg-primary/15 border border-primary/30 flex items-center justify-center shrink-0 text-xs font-bold text-primary">{s.step}</div>
                  <div>
                    <div className="text-sm font-semibold group-hover:text-primary transition-colors">{s.title}</div>
                    <div className="text-[11px] text-muted-foreground mt-0.5 leading-relaxed">{s.desc}</div>
                  </div>
                </div>
              </div>
            </Link>
          ))}
        </div>
      </div>

      {/* Quick links grid */}
      <div>
        <h3 className="text-sm font-semibold mb-3 flex items-center gap-2">
          <ArrowRight className="w-4 h-4 text-primary" /> All Modules
        </h3>
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-2">
          {MODULES.map((m) => {
            const Icon = m.icon;
            return (
              <Link key={m.id} href={m.path}>
                <div className="group rounded-lg border border-border bg-muted/10 p-3 hover:border-primary/30 hover:bg-primary/5 transition-all cursor-pointer text-center">
                  <div className="text-xl mb-1">{m.emoji}</div>
                  <div className="text-xs font-medium group-hover:text-primary transition-colors leading-tight">{m.label}</div>
                  <div className="text-[10px] text-muted-foreground mt-0.5">{m.group}</div>
                </div>
              </Link>
            );
          })}
        </div>
      </div>
    </div>
  );
}

// ─── MODULE GUIDES TAB ─────────────────────────────────────────────────────────
function ModuleGuidesTab() {
  const [search, setSearch] = useState("");
  const [group, setGroup] = useState("All");
  const [expanded, setExpanded] = useState<string | null>(null);

  const filtered = MODULES.filter(m =>
    (group === "All" || m.group === group) &&
    (m.label.toLowerCase().includes(search.toLowerCase()) || m.description.toLowerCase().includes(search.toLowerCase()))
  );

  return (
    <div className="space-y-4">
      <div className="flex flex-col sm:flex-row gap-2">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-muted-foreground" />
          <Input placeholder="Search modules…" value={search} onChange={e => setSearch(e.target.value)} className="pl-9 h-8 text-sm" />
        </div>
        <div className="flex gap-1 flex-wrap">
          {["All", ...MODULE_GROUPS].map(g => (
            <Button key={g} variant={group === g ? "default" : "outline"} size="sm" className="h-8 text-xs" onClick={() => setGroup(g)}>{g}</Button>
          ))}
        </div>
      </div>

      <div className="space-y-2">
        {filtered.map(m => {
          const Icon = m.icon;
          const isOpen = expanded === m.id;
          return (
            <div key={m.id} className={cn("rounded-xl border transition-all", isOpen ? "border-primary/30 bg-primary/5" : "border-border bg-muted/10")}>
              <button
                className="w-full flex items-center gap-3 p-4 text-left"
                onClick={() => setExpanded(isOpen ? null : m.id)}
              >
                <div className="w-9 h-9 rounded-lg bg-muted/40 flex items-center justify-center shrink-0 text-xl">{m.emoji}</div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="font-semibold text-sm">{m.label}</span>
                    <Badge variant="outline" className="text-[10px]">{m.group}</Badge>
                  </div>
                  <p className="text-[11px] text-muted-foreground mt-0.5 line-clamp-1">{m.purpose}</p>
                </div>
                <Link href={m.path} onClick={e => e.stopPropagation()}>
                  <Button variant="ghost" size="sm" className="h-7 text-xs shrink-0 mr-1 hover:text-primary">Open →</Button>
                </Link>
                {isOpen ? <ChevronUp className="w-4 h-4 text-muted-foreground shrink-0" /> : <ChevronDown className="w-4 h-4 text-muted-foreground shrink-0" />}
              </button>

              {isOpen && (
                <div className="px-4 pb-4 space-y-4 border-t border-border/50 pt-4">
                  <p className="text-sm text-muted-foreground leading-relaxed">{m.description}</p>

                  <div className="grid sm:grid-cols-3 gap-4">
                    <div>
                      <div className="text-xs font-semibold text-primary mb-2 flex items-center gap-1.5"><Zap className="w-3.5 h-3.5" />Features</div>
                      <ul className="space-y-1">
                        {m.features.map(f => (
                          <li key={f} className="flex items-start gap-1.5 text-[11px] text-muted-foreground">
                            <CheckCircle2 className="w-3 h-3 text-emerald-400 shrink-0 mt-0.5" />{f}
                          </li>
                        ))}
                      </ul>
                    </div>
                    <div>
                      <div className="text-xs font-semibold text-primary mb-2 flex items-center gap-1.5"><Layers className="w-3.5 h-3.5" />Connected To</div>
                      <div className="flex flex-wrap gap-1">
                        {m.connectedTo.map(c => (
                          <Badge key={c} variant="outline" className="text-[10px]">{c}</Badge>
                        ))}
                      </div>
                    </div>
                    <div>
                      <div className="text-xs font-semibold text-primary mb-2 flex items-center gap-1.5"><Lightbulb className="w-3.5 h-3.5" />Pro Tips</div>
                      <ul className="space-y-1.5">
                        {m.tips.map((t, i) => (
                          <li key={i} className="text-[11px] text-muted-foreground leading-relaxed border-l-2 border-primary/20 pl-2">{t}</li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </div>
              )}
            </div>
          );
        })}
        {filtered.length === 0 && (
          <div className="text-center py-12 text-muted-foreground text-sm">No modules match your search.</div>
        )}
      </div>
    </div>
  );
}

// ─── AI ASSISTANT TAB ──────────────────────────────────────────────────────────
function AIAssistantTab() {
  const [messages, setMessages] = useState<ChatMessage[]>([
    { role: "assistant", text: "Hello! I'm your AEGIS QUANT platform guide. Ask me anything about how the platform works, what any module does, how AI analysis works, or how to deploy your app.\n\nTry one of the suggested questions below or type your own." },
  ]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  function send(text: string) {
    if (!text.trim() || loading) return;
    const userMsg: ChatMessage = { role: "user", text: text.trim() };
    setMessages(prev => [...prev, userMsg]);
    setInput("");
    setLoading(true);
    setTimeout(() => {
      const response = getAIResponse(text.trim());
      setMessages(prev => [...prev, { role: "assistant", text: response }]);
      setLoading(false);
    }, 600 + Math.random() * 400);
  }

  return (
    <div className="flex flex-col h-[600px]">
      {/* Suggested questions */}
      <div className="flex flex-wrap gap-2 mb-4">
        {SUGGESTED_QUESTIONS.map(q => (
          <button
            key={q}
            onClick={() => send(q)}
            className="text-xs px-3 py-1.5 rounded-full border border-border bg-muted/10 hover:border-primary/40 hover:bg-primary/5 hover:text-primary transition-all"
          >
            {q}
          </button>
        ))}
      </div>

      {/* Chat messages */}
      <div className="flex-1 overflow-y-auto rounded-xl border border-border bg-muted/5 p-4 space-y-3 mb-3">
        {messages.map((msg, i) => (
          <div key={i} className={cn("flex gap-3", msg.role === "user" ? "justify-end" : "justify-start")}>
            {msg.role === "assistant" && (
              <div className="w-7 h-7 rounded-lg bg-primary/15 flex items-center justify-center shrink-0 mt-0.5">
                <Brain className="w-3.5 h-3.5 text-primary" />
              </div>
            )}
            <div className={cn(
              "max-w-[80%] rounded-xl px-4 py-3 text-sm whitespace-pre-line leading-relaxed",
              msg.role === "user"
                ? "bg-primary text-primary-foreground rounded-tr-sm"
                : "bg-muted/30 border border-border rounded-tl-sm"
            )}>
              {msg.text}
            </div>
            {msg.role === "user" && (
              <div className="w-7 h-7 rounded-lg bg-muted/40 flex items-center justify-center shrink-0 mt-0.5">
                <MessageSquare className="w-3.5 h-3.5 text-muted-foreground" />
              </div>
            )}
          </div>
        ))}
        {loading && (
          <div className="flex gap-3 justify-start">
            <div className="w-7 h-7 rounded-lg bg-primary/15 flex items-center justify-center shrink-0">
              <Brain className="w-3.5 h-3.5 text-primary animate-pulse" />
            </div>
            <div className="bg-muted/30 border border-border rounded-xl rounded-tl-sm px-4 py-3">
              <div className="flex gap-1">
                {[0, 1, 2].map(i => (
                  <div key={i} className="w-1.5 h-1.5 rounded-full bg-primary/50 animate-bounce" style={{ animationDelay: `${i * 0.15}s` }} />
                ))}
              </div>
            </div>
          </div>
        )}
        <div ref={bottomRef} />
      </div>

      {/* Input */}
      <div className="flex gap-2">
        <Input
          value={input}
          onChange={e => setInput(e.target.value)}
          onKeyDown={e => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); send(input); } }}
          placeholder="Ask about any module, feature, or concept…"
          className="flex-1 text-sm"
        />
        <Button onClick={() => send(input)} disabled={!input.trim() || loading} size="sm" className="shrink-0">
          <Send className="w-4 h-4" />
        </Button>
      </div>
    </div>
  );
}

// ─── KNOWLEDGE BASE TAB ────────────────────────────────────────────────────────
function KnowledgeBaseTab() {
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("All");
  const [expanded, setExpanded] = useState<string | null>(null);

  const filtered = ARTICLES.filter(a =>
    (category === "All" || a.category === category) &&
    (a.title.toLowerCase().includes(search.toLowerCase()) || a.content.toLowerCase().includes(search.toLowerCase()))
  );

  const DIFF_COLORS: Record<string, string> = {
    Beginner: "text-emerald-400 border-emerald-500/30",
    Intermediate: "text-yellow-400 border-yellow-500/30",
    Advanced: "text-red-400 border-red-500/30",
  };

  return (
    <div className="space-y-4">
      <div className="flex flex-col sm:flex-row gap-2">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-muted-foreground" />
          <Input placeholder="Search articles…" value={search} onChange={e => setSearch(e.target.value)} className="pl-9 h-8 text-sm" />
        </div>
        <div className="flex gap-1 flex-wrap">
          {ARTICLE_CATEGORIES.map(c => (
            <Button key={c} variant={category === c ? "default" : "outline"} size="sm" className="h-8 text-xs" onClick={() => setCategory(c)}>{c}</Button>
          ))}
        </div>
      </div>

      <div className="grid sm:grid-cols-2 gap-2">
        {filtered.map(a => {
          const isOpen = expanded === a.id;
          return (
            <div key={a.id} className={cn("rounded-xl border transition-all", isOpen ? "border-primary/30 bg-primary/5 sm:col-span-2" : "border-border bg-muted/10")}>
              <button className="w-full flex items-start gap-3 p-4 text-left" onClick={() => setExpanded(isOpen ? null : a.id)}>
                <div className="w-8 h-8 rounded-lg bg-muted/40 flex items-center justify-center shrink-0">
                  <BookOpen className="w-4 h-4 text-primary" />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="font-semibold text-sm">{a.title}</span>
                    <Badge variant="outline" className={cn("text-[10px]", DIFF_COLORS[a.difficulty])}>{a.difficulty}</Badge>
                    <Badge variant="outline" className="text-[10px]">{a.category}</Badge>
                  </div>
                </div>
                {isOpen ? <ChevronUp className="w-4 h-4 text-muted-foreground shrink-0 mt-0.5" /> : <ChevronDown className="w-4 h-4 text-muted-foreground shrink-0 mt-0.5" />}
              </button>
              {isOpen && (
                <div className="px-4 pb-4 pt-2 border-t border-border/50">
                  <p className="text-sm text-muted-foreground leading-relaxed whitespace-pre-line">{a.content}</p>
                </div>
              )}
            </div>
          );
        })}
        {filtered.length === 0 && (
          <div className="sm:col-span-2 text-center py-12 text-muted-foreground text-sm">No articles match your search.</div>
        )}
      </div>
    </div>
  );
}

// ─── FAQ TAB ──────────────────────────────────────────────────────────────────
function FAQTab() {
  const [expanded, setExpanded] = useState<number | null>(null);
  const [search, setSearch] = useState("");

  const filtered = FAQ_ITEMS.filter(f =>
    f.q.toLowerCase().includes(search.toLowerCase()) || f.a.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="space-y-4">
      <div className="relative">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-muted-foreground" />
        <Input placeholder="Search FAQ…" value={search} onChange={e => setSearch(e.target.value)} className="pl-9 h-8 text-sm" />
      </div>

      <div className="space-y-2">
        {filtered.map((item, i) => {
          const isOpen = expanded === i;
          return (
            <div key={i} className={cn("rounded-xl border transition-all", isOpen ? "border-primary/30 bg-primary/5" : "border-border bg-muted/10")}>
              <button className="w-full flex items-start gap-3 p-4 text-left" onClick={() => setExpanded(isOpen ? null : i)}>
                <div className="w-6 h-6 rounded-full bg-primary/15 flex items-center justify-center shrink-0 mt-0.5">
                  <HelpCircle className="w-3.5 h-3.5 text-primary" />
                </div>
                <span className="flex-1 text-sm font-medium">{item.q}</span>
                {isOpen ? <ChevronUp className="w-4 h-4 text-muted-foreground shrink-0 mt-0.5" /> : <ChevronDown className="w-4 h-4 text-muted-foreground shrink-0 mt-0.5" />}
              </button>
              {isOpen && (
                <div className="px-4 pb-4 pt-2 border-t border-border/50">
                  <p className="text-sm text-muted-foreground leading-relaxed">{item.a}</p>
                </div>
              )}
            </div>
          );
        })}
        {filtered.length === 0 && (
          <div className="text-center py-12 text-muted-foreground text-sm">No FAQ items match your search.</div>
        )}
      </div>
    </div>
  );
}

// ─── MAIN PAGE ─────────────────────────────────────────────────────────────────
export default function Guidance() {
  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="text-2xl font-black flex items-center gap-2.5">
            <Map className="w-6 h-6 text-primary" />
            Guidance Center
          </h1>
          <p className="text-sm text-muted-foreground mt-1">
            Platform documentation, AI assistant, knowledge base, and learning resources.
          </p>
        </div>
        <Badge variant="outline" className="text-primary border-primary/30 shrink-0 mt-1">
          <Sparkles className="w-3 h-3 mr-1" /> Module 16
        </Badge>
      </div>

      <Tabs defaultValue="overview">
        <TabsList className="flex-wrap h-auto gap-1">
          <TabsTrigger value="overview" className="text-xs">
            <Map className="w-3.5 h-3.5 mr-1.5" />Overview
          </TabsTrigger>
          <TabsTrigger value="modules" className="text-xs">
            <Layers className="w-3.5 h-3.5 mr-1.5" />Module Guides
          </TabsTrigger>
          <TabsTrigger value="assistant" className="text-xs">
            <Brain className="w-3.5 h-3.5 mr-1.5" />AI Assistant
          </TabsTrigger>
          <TabsTrigger value="knowledge" className="text-xs">
            <BookOpen className="w-3.5 h-3.5 mr-1.5" />Knowledge Base
          </TabsTrigger>
          <TabsTrigger value="faq" className="text-xs">
            <HelpCircle className="w-3.5 h-3.5 mr-1.5" />FAQ
          </TabsTrigger>
        </TabsList>

        <TabsContent value="overview" className="mt-4"><OverviewTab /></TabsContent>
        <TabsContent value="modules" className="mt-4"><ModuleGuidesTab /></TabsContent>
        <TabsContent value="assistant" className="mt-4"><AIAssistantTab /></TabsContent>
        <TabsContent value="knowledge" className="mt-4"><KnowledgeBaseTab /></TabsContent>
        <TabsContent value="faq" className="mt-4"><FAQTab /></TabsContent>
      </Tabs>
    </div>
  );
}
