import { useState } from "react";
import { 
  useListSignals,
  useCreateSignal,
  getListSignalsQueryKey
} from "@workspace/api-client-react";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { formatDate } from "@/lib/format";
import { Signal as SignalIcon, ArrowUpRight, ArrowDownRight, Minus } from "lucide-react";

export default function Signals() {
  const { data: signals, isLoading } = useListSignals(
    { limit: 50 },
    { query: { queryKey: getListSignalsQueryKey({ limit: 50 }), refetchInterval: 10000 } }
  );

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">Signals Feed</h1>
        <p className="text-sm text-muted-foreground">Real-time trading signals generated by models</p>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {isLoading ? (
          Array.from({ length: 6 }).map((_, i) => (
            <Card key={i} className="flex flex-col">
              <CardHeader className="pb-2">
                <div className="flex justify-between items-center">
                  <Skeleton className="h-6 w-20" />
                  <Skeleton className="h-5 w-16" />
                </div>
              </CardHeader>
              <CardContent className="flex-1 pb-2">
                <Skeleton className="h-10 w-full mb-4" />
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-2/3 mt-2" />
              </CardContent>
            </Card>
          ))
        ) : signals?.length === 0 ? (
          <div className="col-span-full py-12 text-center text-muted-foreground">
            No signals generated recently
          </div>
        ) : (
          signals?.map((signal) => {
            const isBuy = signal.signalType === "buy";
            const isSell = signal.signalType === "sell";
            
            return (
              <Card key={signal.id} className="flex flex-col border-border hover:border-primary/50 transition-colors">
                <CardHeader className="pb-2">
                  <div className="flex justify-between items-center">
                    <span className="font-mono font-bold text-lg">{signal.symbol}</span>
                    <Badge variant="outline" className={
                      isBuy ? "border-success text-success" : 
                      isSell ? "border-destructive text-destructive" : 
                      "border-warning text-warning"
                    }>
                      {isBuy ? <ArrowUpRight className="w-3 h-3 mr-1" /> : 
                       isSell ? <ArrowDownRight className="w-3 h-3 mr-1" /> : 
                       <Minus className="w-3 h-3 mr-1" />}
                      {signal.signalType.toUpperCase()}
                    </Badge>
                  </div>
                </CardHeader>
                <CardContent className="flex-1 pb-2 space-y-4">
                  <div>
                    <div className="flex justify-between text-xs mb-1">
                      <span className="text-muted-foreground">Confidence</span>
                      <span className="font-medium">{signal.confidence}%</span>
                    </div>
                    <Progress value={signal.confidence} className="h-1.5" />
                  </div>
                  
                  <div className="text-sm">
                    <span className="text-muted-foreground block mb-1">Reason</span>
                    <p className="line-clamp-2">{signal.reason || "Algorithm output"}</p>
                  </div>
                </CardContent>
                <CardFooter className="pt-2 border-t border-border flex justify-between items-center text-xs text-muted-foreground">
                  <span>{signal.strategyName || "Manual"}</span>
                  <span className="font-mono">{formatDate(signal.createdAt)}</span>
                </CardFooter>
              </Card>
            );
          })
        )}
      </div>
    </div>
  );
}
